version: '3'
services:
  pi-db:
    image: postgres:12
    ports:
      - "127.0.0.1:25432:5432"
    env_file:
      - .docker.env
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  pi-data-collector:
    depends_on:
      - pi-db
    build:
      context: ./
    env_file:
      - .docker.env
    environment:
      - PGHOST=pi-db
      - PGPORT=5432
  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  postgres-storage:
  grafana-storage: